### ISSUE TITLE
Working docker image to run electron test headless

### ISSUE THREAD

**Issue by zhex900** [electron-userland/spectron#1021]
Hi,

Is there a working example of how to to run electron tests in a docker container headlessly?

**Comment by zhex900** [comment]
I have made a little progress but I still cannot run the tests in the docker container.

The above error meant my electron app did not even run . 
I fixed it by doing these

```
chown root /out/App/chrome-sandbox
chmod 4755 /out/App/chrome-sandbox
```

Now I get a different error 

```
    waitUntilWindowLoaded waitUntil condition failed with the following reason: invalid session id

      at node_modules/webdriverio/build/commands/browser/waitUntil.js:26:15
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:63:29)
      at Browser.waitUntilWindowLoaded (node_modules/@wdio/utils/build/shim.js:63:29)


  ● Test suite failed to run

    invalid session id: invalid session id

      at Object.getErrorFromResponseBody (node_modules/webdriver/build/utils.js:94:12)
      at WebDriverRequest._request (node_modules/webdriver/build/request.js:134:31)
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:63:29)
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:63:29)
      at Browser.electron.remote.app.quit (node_modules/@wdio/utils/build/shim.js:63:29)
````

My electron app did run this time. I can see the logs. I guess webdriver cannot connect to it.

**Comment by zhex900** [comment]
Here are more logs
```
    console.warn
      2021-08-11T04:38:32.577Z WARN webdriver: Request failed with status 500 due to unknown error: session deleted because of page crash
      from unknown error: cannot determine loading status
      from tab crashed
        (Session info: chrome=91.0.4472.106)

````

**Comment by GeorgDangl** [comment]
FYI, we just updated an app from Electron 11 to 13, and could no longer get Spectron to run the E2E tests in a Docker container. We spent half a day on trying to resolve this, but without luck. Here's the Dockerfile we're using, I think that's mostly just cobbled together from some places until it finally worked😀

```
FROM node:14 AS node

FROM node AS headless
RUN apt-get update && \
    apt-get install -y xvfb \
    libgbm1 \
    libxss1 \
    libnss3 \
    libgtk-3-dev \
    libasound2-dev \
    unzip \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*

FROM headless AS final
ADD docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
RUN dos2unix /docker-entrypoint.sh
EXPOSE 9515
ENV ELECTRON_ENABLE_STACK_DUMPING=true
ENV ELECTRON_ENABLE_LOGGING=true
ENTRYPOINT [ "/docker-entrypoint.sh" ]
```

As for getting the tests running: What we actually did now was switching to https://github.com/microsoft/playwright. I can't yet vouch for it, but the setup was incredibly easy.

**Comment by zhex900** [comment]
@GeorgDangl 
So you switched to `playwright` to test your electron?

**Comment by GeorgDangl** [comment]
Yeah, exactly. We just have a handful of E2E tests, and we’re lucky to have a small abstraction layer for the Spectrum API, so switching to it was quite fast.

**Comment by zhex900** [comment]
How did you run playWright headlessly ? https://github.com/microsoft/playwright/issues/2609 Can you help me?

**Comment by GeorgDangl** [comment]
Well, strictly speaking it doesn't run headless, it just runs in Docker with xvfb without showing an UI. So the Dockerfile and the entrypoint are similar to what you have.

We've just got this for a common setup:

```typescript
const path = require('path');

import { ElectronApplication, _electron } from 'playwright';

export default function setup(): void {
  beforeEach(async function () {
    this.electronApp = await _electron.launch({
      args: ['--disable_splash_screen', path.join(__dirname, '..')]
    });
  });

  afterEach(function () {
    if (this.electronApp) {
      return this.electronApp.close();
    }
  });
}
```

And then this (shortened) for the tests:

```typescript
import { E2eAppConfigService } from './e2e-app-config-service';
import { Page } from 'playwright';
import commonSetup from './common-setup';
import { expect } from 'chai';

describe('myproject-ui App', function () {
  commonSetup.apply(this);

  let page: Page;
  let appConfig: { backendUrl: string };

  beforeEach(async function () {
    page = await this.electronApp.firstWindow();
    appConfig = new E2eAppConfigService().getAppConfig();
    await ensureUpdateCheckNotificationIsDisabled();
  });

  it('should display My Project Header in header', async function () {
    const text = await getText('dangl-header h1');
    expect(text).to.contain('some header text');
  });

  it('creates initial windows', async function () {
    const windows = await this.electronApp.windows();
    expect(windows.length).to.equal(1);
  });

});

```

**Comment by GeorgDangl** [comment]
I've summarized it a bit here in this blog post: https://blog.dangl.me/archive/running-fully-automated-e2e-tests-in-electron-in-a-docker-container-with-playwright/

**Comment by zhex900** [comment]
@GeorgDangl Thank you for sharing your post. 
So you can run playWright electron test in docker headless?

I read your blog. But I still cannot get my tests to run. 

Are you able to give me so help? Have you ever run into ` Unable to open X display.`

https://github.com/microsoft/playwright/issues/8198

**Comment by GeorgDangl** [comment]
Sorry, didn't run into that problem before, but I replied to your other issue in the Playwright repository.
