### ISSUE TITLE
Error running on bare-bones testing setup

### ISSUE THREAD

**Issue by AdrianoFerrari** [electron-userland/spectron#277]
Running on Linux, with these versions:
```
    "electron": "^2.0.0-beta.4",
    "spectron": "^3.8.0",
    "mocha": "^5.0.5",
```

I get the following error regarding inAppPurchase module:
```
     unknown error: The inAppPurchase module can only be used on macOS
Error: The inAppPurchase module can only be used on macOS
    at Object.<anonymous> (/home/adriano/code/learn/gingko/client/node_modules/electron/dist/resources/electron.asar/browser/api/in-app-purchase.js:4:9)
    at Object.<anonymous> (/home/adriano/code/learn/gingko/client/node_modules/electron/dist/resources/electron.asar/browser/api/in-app-purchase.js:16:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.get [as inAppPurchase] (/home/adriano/code/learn/gingko/client/node_modules/electron/dist/resources/electron.asar/browser/api/exports/electron.js:11:16)
  Error: An unknown server-side error occurred while processing the command.
      at execute(<Function>, "require") - api.js:73:26
```

Steps to reproduce:
```
git clone -b testing git@github.com:gingko/client.git
cd client
yarn install
yarn build
yarn test
```

I found that a one-line change here fixes this (though likely breaks `inAppPurchase` tests):
https://github.com/electron/spectron/blob/master/lib/api.js#L88
```diff
--- a/lib/api.js
+++ b/lib/api.js
@@ -86,6 +86,7 @@ Api.prototype.loadApi = function () {
         case 'deprecate':
         case 'deprecations':
         case 'hideInternalModules':
+        case 'inAppPurchase':
         case 'Tray':
           return true
       }
```

Can you point me in the right direction for a fix here, @jkleinsc ?

**Comment by jkleinsc** [comment]
@AdrianoFerrari I think your fix is close.  The following would allow it to work for MacOS:
```
        case 'inAppPurchase':
          return process.platform !== 'darwin'
```
