### ISSUE TITLE
App doesn't open with Spectron 9.0.0 and Electron 7.1.0 , the platform is Windows.

### ISSUE THREAD

**Issue by Ankitr19** [electron-userland/spectron#485]
I have a test written in Spectron, and I use both Mac and Windows platform for the testing purpose. So, the test works completely fine on Mac, but in case of Windows, the app is not able to start.

The error looks like this:-

`1) Application Launch
       "before all" hook for "Shows an initial window":
     Client initialization failed after 10 attempts: RuntimeError Client initialization failed after 10 attempts: 
  Error: unknown error: Failed to create a Chrome process.
    (Driver info: chromedriver=78.0.3905.1 (c7cce564a78f7c44042856c33e2f3dab0bc4307d-refs/heads/master@{#703739}),platform=Windows NT 10.0.17763 x86_64)
      at new RuntimeError (node_modules\webdriverio\build\lib\utils\ErrorHandler.js:143:12)
      at Request._callback (node_modules\webdriverio\build\lib\utils\RequestHandler.js:318:39)
      at Request.self.callback (node_modules\request\request.js:185:22)
      at Request.EventEmitter.emit (domain.js:476:20)
      at Request.<anonymous> (node_modules\request\request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:476:20)
      at IncomingMessage.<anonymous> (node_modules\request\request.js:1083:12)
      at IncomingMessage.EventEmitter.emit (domain.js:476:20)
      at endReadableNT (_stream_readable.js:1168:12)
      at processTicksAndRejections (internal/process/task_queues.js:77:11)`

**Comment by tboulis** [comment]
Getting the same error, how did you fixed it @Ankitr19 ?
