### ISSUE TITLE
Error: ChromeDriver did not start within 5000ms on spectron 11.0.0

### ISSUE THREAD

**Issue by xland** [electron-userland/spectron#640]
spectron:`^11.0.0`
electron:`^9.0.0`
mocha:`^8.0.1`
windows:10
ErrorInfo:
```
Application launch
       "before each" hook for "shows an initial window":
     Error: ChromeDriver did not start within 5000ms
      at E:\code\desktop-proj\node_modules\spectron\lib\chrome-driver.js:63:25
      at Request._callback (node_modules\spectron\lib\chrome-driver.js:121:23)
      at self.callback (node_modules\request\request.js:185:22)
      at Request.EventEmitter.emit (domain.js:482:12)
      at Request.onRequestError (node_modules\request\request.js:877:8)
      at ClientRequest.EventEmitter.emit (domain.js:482:12)
      at Socket.socketErrorListener (_http_client.js:426:9)
      at Socket.EventEmitter.emit (domain.js:482:12)
      at emitErrorNT (internal/streams/destroy.js:92:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Test Code:
```javascript
const Application = require('spectron').Application
const assert = require('assert')
const electronPath = require('electron')
const path = require('path')

describe('Application launch', function() {
  this.timeout(10000)

  beforeEach(function() {
    this.app = new Application({
      path: electronPath,
      args: [path.join(__dirname, '..')]
    })
    return this.app.start()
  })

  afterEach(function() {
    if (this.app && this.app.isRunning()) {
      return this.app.stop()
    }
  })

  it('shows an initial window', function() {
    return this.app.client.getWindowCount().then(function(count) {
      assert.equal(count, 1)
    })
  })
})

```

**Comment by ckcks12** [comment]
+1

**Comment by xland** [comment]
ChromeDriver is not installed correctly.
So just close this issue.

**Comment by GrzegorzWziatek** [comment]
@xland what did you do to make it working again? I've hit same issue

**Comment by xland** [comment]
@GrzegorzWziatek 

try delete your node_modules
and run `npm install`
