### ISSUE TITLE
linux-arm64 does not seem to work, perhaps due to an underlying chromedriver issue?

### ISSUE THREAD

**Issue by starpit** [electron-userland/spectron#745]
# Summary

When trying the sample method suggested on your github README (but also for our project), spectron fails to launch on arm64 (aarch64) due to: "unknown error: DevToolsActivePort file doesn't exist". (See the full logs below). Everything works fine on linux x86, and darwin x86.

## What we tried

We have tried adding `--headless`, `--no-sandbox`, `--disable-dev-shm-usage`, and all of the other command line options suggested by searches on this topic... to no avail.

When trying the chromedriver command line (from the chromedriver log below) directly, i.e. by hand, it seems to come up without failure. I don't know why, with spectron in the mix, things fail.

# Full Logs

## Stderr:

```
  1) Application launch
       "before each" hook for "shows an initial window":
     Error: Failed to create session.
unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/ubuntu/spectest/node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
      at Object.startWebDriverSession (node_modules/webdriver/build/utils.js:34:15)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## chromedriver log

```
[1603448122.574][INFO]: Launching chrome: /home/ubuntu/spectest/node_modules/spectron/lib/launcher.js --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --password-store=basic --remote-debugging-port=0 --spectron-arg0=/home/ubuntu/spectest --spectron-path=/home/ubuntu/spectest/node_modules/electron/dist/electron\
 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.kp2Qzv data:,
_stream_readable.js:684
    dest.end();
         ^

TypeError: dest.end is not a function
    at Socket.onend (_stream_readable.js:684:10)
    at Object.onceWrapper (events.js:420:28)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

## strace -f log

Launching the test via `strace -f npm test` yields some odd lines, e.g.

```
[pid 80295] sendto(17, "HTTP/1.1 500 Internal Server Err"..., 490, MSG_NOSIGNAL, NULL, 0 <unfinished ...>
```

**Comment by egor-romanov** [comment]
@starpit Hello! 

Could you please tell me why have you closed this issue? 
Have you figured this out somehow?

Thank you in advance!

**Comment by starpit** [comment]
Howdy. We still have yet to get our project (electron 7, spectron 9) to the point where tests work with arm64 builds (manual testing seems fine).

We then tried using the stock electron project with electron 10.latest, and spectron 12), and it worked.

So... for now, we have chalked this up to some bug in chromedriver that was fixed by the upgrades included in the spectron 9->12 transition.

But we'd love to be proven wrong :)

**Comment by egor-romanov** [comment]
Ok, got you!

I am trying to resolve the similar issue with our project (electron 8, spectron 10) and it seems like I am running out of bullets. 

The most annoying thing is that spectron can launch an app packed to js main file by webpack, but cannot launch the same app that is packaged in appimage or whatever else linux ready. 

I think we have to try upgrading to electron 10 and see if it helps 👍 

Thank you for your answer :)
