### ISSUE TITLE
Cannot run test with electron with react and jest

### ISSUE THREAD

**Issue by repl-shenoy-sukumaran** [electron-userland/spectron#812]
# Webdriver error prevent the app from starting (but actually apps opens)

```
 javascript error: javascript error: Cannot convert undefined or null to object
      (Session info: chrome=87.0.4280.60)

       8 | 
       9 |   beforeEach(async () => {
    > 10 |     await app.start();
         |     ^
      11 |   })
      12 | 
      13 |   afterEach(async () => {

      at Object.getErrorFromResponseBody (node_modules/webdriver/build/utils.js:94:12)
      at WebDriverRequest._request (node_modules/webdriver/build/request.js:134:31)
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:63:29)
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:63:29)
      at Object.<anonymous> (src/tests/lauch.test.js:10:5)
```

## Versions

Electron: ^11.0.0
Spectron: ^13.0.0

## Steps to reproduce**

- Clone the repo https://github.com/repl-shenoy-sukumaran/spectron-electron-react-issue
- npm install
- npm run build
- npm run dist
- npm run react-test

![image](https://user-images.githubusercontent.com/13564819/102864583-64927f80-445a-11eb-9963-af12936e9ad2.png)

**Comment by movitto** [comment]
See #738 for a hotfix / workaround
