### ISSUE TITLE
electron:11.0.0,spectron:13.0.0 ran electron test demo, javascript error: javascript error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by yoresu** [electron-userland/spectron#813]
I am using electron: 11.0.0, spectron: 13.0.0 to run the test demo of electron,
javascript error: javascript error: Cannot convert undefined or null to object
   (Session info: chrome=87.0.4280.60)
       at Object.getErrorFromResponseBody (node_modules\webdriver\build\utils.js:94:12)
       at WebDriverRequest._request (node_modules\webdriver\build\request.js:134:31)
       at processTicksAndRejections (internal/process/task_queues.js:93:5)
       at async Browser.wrapCommandFn (node_modules\@wdio\utils\build\shim.js:63:29)
       at async Browser.wrapCommandFn (node_modules\@wdio\utils\build\shim.js:63:29)

![image](https://user-images.githubusercontent.com/76470880/102865671-150b7e00-4471-11eb-991b-96af69b97214.png)

**Comment by EnSec4Git** [comment]
I'm having the exact same issue (down to the stack trace line / character numbers).
If this is relevant, I started from the [Electron Vue](https://github.com/SimulatedGREG/electron-vue) scaffolding and updated all of the packages.

At this point, the dev process is rather opaque due to the complicated pipeline - Webpack, TypeScript, Babel, etc.
Can anyone recommend any way to get further visibility into this issue? @yoresu did you use the same scaffolding?

**Comment by movitto** [comment]
See #738 for a hotfix / workaround.
