### ISSUE TITLE
RequestError: connect ECONNREFUSED 127.0.0.1:9515

### ISSUE THREAD

**Issue by jeffcrouse** [electron-userland/spectron#862]
I suddenly started getting this error in some mocha tests that had been running just fine.  The code is something like this:

```
var link = this.app.client.$('#blah')
await link.waitForExist({ timeout: 30000 });
await link.click();
```

and the full error is

```
RequestError: socket hang up
    at ClientRequest.<anonymous> (/Users/[redacted]/node_modules/webdriver/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.origin.emit (/Users/[redacted]/node_modules/webdriver/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketOnEnd (_http_client.js:493:9)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I put some logging in and it seems to be happening on the first line, which is weird because I use the exact same syntax in a previous test and it works just fine. I have double-checked that #blah does, in fact, exist in the DOM. My instinct is that something I did is causing the socket to hang up, but the "socket hang up" message is the only hint I have. 

This same error occurs on both Mac and Windows. I am using Spectron ^11.1.0 with Electron ^9.1.1. 

Elsewhere (in the Webdriver issues, I think) I have found something about a problem with the version of "got" that is used, but I didn't have any luck going down that road. 

I can't, for the life of me, find anything in a diff that would have caused this.  

Thanks in advance for any help.

**Comment by sytolk** [comment]
The same error in github actions platform Windows this happened after update spectron from v12 to v13

```
github-actions
/ Jest Report Electron
TST04 - Testing the tag library: > TST0404 - Change default tag group tag colors [web,minio,electron]
RequestError: connect ECONNREFUSED 127.0.0.1:9515


Stacktrace:
    at ClientRequest.<anonymous> (node_modules\webdriver\node_modules\got\dist\source\core\index.js:940:25)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at ClientRequest.origin.emit (node_modules\webdriver\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:427:9)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal\streams\destroy.js:92:8)
    at emitErrorAndCloseNT (internal\streams\destroy.js:60:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
```

but I think that error is from WDIO update in new spectron. Its have the same error in the same test testing with wdio without spectron.

```
github-actions
/ Jest Report Web
TST04 - Testing the tag library: > TST0404 - Change default tag group tag colors [web,minio,electron]
RequestError: connect ECONNREFUSED 127.0.0.1:9515


Stacktrace:
    at ClientRequest.<anonymous> (node_modules\webdriver\node_modules\got\dist\source\core\index.js:940:25)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at ClientRequest.origin.emit (node_modules\webdriver\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:427:9)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal\streams\destroy.js:92:8)
    at emitErrorAndCloseNT (internal\streams\destroy.js:60:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
```

**Comment by Shirisha8812** [comment]
I am also facing the same issue.
My webdriver version is 6.0.1
I added chrome capabilities as 
goog:chromeOptions': {
            args: [ '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage --window-size=1920,1080', '--disable-translate', '--disable-extensions', '--disable-background-networking', '--disable-sync', '--disable-default-apps', '--mute-audio', '--no-first-run', '--disable-prompt-on-repost']
        }

Any help is appreciated. Thanks

**Comment by shivamrsoft** [comment]
I am also facing the same issue.

**Comment by evertonlperes** [comment]
> I am also facing the same issue.
> 
> My webdriver version is 6.0.1
> 
> I added chrome capabilities as 
> 
> goog:chromeOptions': {
> 
>             args: [ '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage --window-size=1920,1080', '--disable-translate', '--disable-extensions', '--disable-background-networking', '--disable-sync', '--disable-default-apps', '--mute-audio', '--no-first-run', '--disable-prompt-on-repost']
> 
>         }
> 
> 
> 
> Any help is appreciated. Thanks

My 2 cents... move to Playwright.
I didn't face any of those weird Chrome issue after refactoring and implementes Playwright.

**Comment by bhadmus** [comment]
A node change did it for me, I installed `v16.14.0` via `nvm` and also downgraded `appium` to `2.0.0-beta.46` and it worked
